#!/usr/bin/perl
use warnings;
use strict;

my $dirname = "./songs";
my $final = '';

opendir( my $data_dh, $dirname ) or die "Cannot open $dirname\n";
while ( my $name = readdir($data_dh) ) {
    next if ( $name eq '.' or $name eq '..' );
    my $full_path = "${dirname}/${name}";
    processFile($full_path);
}
closedir($data_dh);

sub processFile{
    open(FH, '<', $_[0]) or die $!;
    my $linenumber = 0;

    while(<FH>){
        $linenumber++;
        $_ =~ s/[\n\r]//g;
        if ($linenumber == 1){
            $final = "${final}\\beginsong{$_}\n";
        } elsif ($linenumber == 2){
            if ($_ ne "")
            {
            }

        } elsif ($linenumber == 3){
            if ($_ ne "")
            {
                $final = "${final}$_\n\n";
            }
        } else {
            $final = "${final}$_\n\n";
        }
    }
    $final = "${final}\\endsong\n\n";
}



my $filename = './src/autogenerated.tex';
open(FH, '>', $filename) or die $!;
print FH $final;
close(FH);

print "Writing to file successfully!\n";