name: 'Build LaTex Document'
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run preprocessor
        run: perl generate.pl
      - name: Run Tectonic
        run: tectonic -X build
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: /home/runner/work/folksong-anthology/folksong-anthology/build/main/main.pdf
